inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  # NewCops: enable
  Exclude:
    - bin/*
    - config/**/*
    - db/migrate/20230821182611_add_service_name_to_active_storage_blobs.active_storage.rb
    - db/migrate/20230821182612_create_active_storage_variant_records.active_storage.rb
    - db/migrate/20230829170436_devise_create_users.rb
    - db/schema.rb
    - Rakefile

Rails/BulkChangeTable:
  Exclude:
    - db/migrate/20231005175303_add_hidden_and_batch_code_to_questions.rb

Rails/ReversibleMigration:
  Exclude:
    - db/migrate/20230726192619_add_author_to_repositories.rb
    - db/migrate/20230911185221_remove_remember_created_at.rb
    - db/migrate/20231004143201_remove_step_from_logs.rb

Rails/SkipsModelValidations:
  AllowedMethods: [ toggle! ]

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - app/models/administrator.rb
    - app/models/author.rb
    - app/models/repository.rb

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
