# This configuration file is only used 
# to demonstrate how to deploy in a production environment

services:
  db:
    image: postgres:15-alpine
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=knewhub
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    volumes:
      - redis_vol:/var/lib/redis/data
    ports:
      - 6379

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"

  # background-service
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=knewhub
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    volumes:
      - repos_vol:/rails/repos
    depends_on:
      - db
      - redis
      - maildev

  # backend-instance-1
  web-b:
    build: .
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=knewhub
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    volumes:
      - repos_vol:/rails/repos
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - maildev

  # backend-instance-2
  web-a:
    build: .
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=knewhub
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    volumes:
      - repos_vol:/rails/repos
    ports:
      - "3002:3000"
    depends_on:
      - db
      - redis
      - sidekiq
      - maildev

volumes:
  db_vol:
  redis_vol:
  repos_vol:
